version: 2.0
jobs:
  testflow:
    docker:
      - image: circleci/ruby:2.2 
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/testing-workflows
    steps:
      - run: echo "A first hello"
workflows:
  version: 2
  build:
    jobs:
      - testflow
